### ISSUE TITLE
doesn't build on Fedora

### ISSUE THREAD

**Issue by hypatia-of-sva** [jon-lipstate/pico#1]
Produces the compile error:

```
/home/sva/Downloads/pico-master/linux.odin(27:12) Undeclared name: VMIN
        term.c_cc[VMIN] = 0
                  ^~~^
/home/sva/Downloads/pico-master/linux.odin(28:12) Undeclared name: VTIME
        term.c_cc[VTIME] = 0
                  ^~~~^
```

I originally encountered this when trying to use linux.odin for my own project, and had the same issue. 

According to the manpage:
https://man7.org/linux/man-pages/man3/termios.3.html
VMIN and VTIME are values to be set, not constants. Should they be set in linux.odin, or is there some other way you think this should be dealt with?

Edit: Apparently I used grep incorrectly, and also misunderstood the manpage; with  `grep -r VMIN ./* ; grep -r VTIME ./*`
I fount the following defintions in <bits/termios-cc_c.h>:
```

/* c_cc characters */
#define VINTR 0
#define VQUIT 1
#define VERASE 2
#define VKILL 3
#define VEOF 4
#define VTIME 5
#define VMIN 6
#define VSWTC 7
#define VSTART 8
#define VSTOP 9
#define VSUSP 10
#define VEOL 11
#define VREPRINT 12
#define VDISCARD 13
#define VWERASE 14
#define VLNEXT 15
#define VEOL2 16
```

As the issue stands, should the values for VMIN and VTIME just be copied into the code?

**Comment by jasonKercher** [comment]
`VTIME` and `VMIN` are constants that index into `c_cc`.  Looks like they are just missing.  I've actually recreated this struct myself for a different project.  In my case, I made `c_cc` a sparse enumerated array with this enum:

```odin
NCCS :: 32
C_Cc_Idx :: enum {
        VINTR,
        VQUIT,
        VERASE,
        VKILL,
        VEOF,
        VTIME,
        VMIN,
        VSWTC,
        VSTART,
        VSTOP,
        VSUSP,
        VEOL,
        VREPRINT,
        VDISCARD,
        VWERASE,
        VLNEXT,
        VEOL2,
        _end = NCCS - 1,
}
```

From the struct definition:
```odin
c_cc:     #sparse [C_Cc_Idx]cc_t,
```

**Comment by hypatia-of-sva** [comment]
Yes, I made a mistake, sorry for the unclear edits. If they are standard, I will just add
```
VTIME :: 5
VMIN :: 6
```
to my version of the code, and see if it fixes it

**Comment by hypatia-of-sva** [comment]
Update: this was indeed the only issue, it builds now and runs fine

**Comment by kalsprite** [comment]
Apologies, I got overzealous in cleaning unused items brought over from the header file. I will push a commit this evening that restores them.
